### PR TITLE
Add addtional functionality to value example

### PR DESCRIPTION
**Pull request by jordanjones243**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #89 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

* Add new event `auroMenu-selectValueFailure`, the select component to input an invalid value, as well as giving `auro-select` the `error` attribute when fired.
* Add new event `auroMenu-selectValueReset`, causing `auro-select` to reset to its default state.
* Implement additional functionality to the `auro-select` API `value` example.
* Add tests to ensure programmatically setting value to a valid value, invalid value and undefined work properly.

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Comment by blackfalcon** [comment]
@jordanjones243 

I see in the code and the test that there is the intent to change the values of the selected value, but what is supposed to be happening in the demo here? 

Screen Shot 2022-08-25 at 5 00 18 PM

**Comment by jordanjones243** [comment]
> @jordanjones243
> 
> I see in the code and the test that there is the intent to change the values of the selected value, but what is supposed to be happening in the demo here?
> 
> Screen Shot 2022-08-25 at 5 00 18 PM

By changing the `value` attribute of select, we can change the content of select through the execution of the program. Similar to combobox, Jason asked me to create the same exact example for both select and datepicker. The demo is supposed to represent setting the `value` option programatically. Jason wanted to demonstrate how the code handles not only valid options, but also what happens when someone passes in an invalid and undefined value. I believe this example is more to demonstrate a use case for developers using these auro components, rather than users of the AScom site.

**Comment by blackfalcon** [comment]
@jordanjones243 I am understanding that, but... when I click the buttons, nothing is happening that I can see. No visual change, no alert or console log? What is supposed to happen when I click the buttons?

**Comment by jordanjones243** [comment]
@blackfalcon Oh I see... on my localhost, its working as intended. When you click on "Set Value to Valid Option" the text should change to Arrival, with selected option being changed to Arrival as well.  The "Set Value to Invalid Option" should change the text to "Dragon Fruit" and trigger the error attribute. The Undefined option should just reset the entire component to the base state without a preset value.

**Comment by jason-capsule42** [comment]
@blackfalcon For me this works correctly in localhost as well. I pulled it down, ran `npm i` and then `npm run dev` and the example buttons change the value just as I would expect.

**Review by blackfalcon — DISMISSED** [review]

**Review by jason-capsule42 — APPROVED** [review]

**Pull request merged**
