### PR TITLE
Fix dropdown positioning issue inside auro-dialog

### PR DESCRIPTION
**Pull request by fajar-apri-alaska**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** #187 

## Summary:

- This PR addresses the positioning issue of `auro-dropdown` when `auro-select` is placed inside `auro-dialog` component.

Please see below videos for related fixes:

https://github.com/AlaskaAirlines/auro-select/assets/124668226/1f7095a6-0ca9-4ee6-ae31-b01ec29539fc

Also, the fixes seems to not creating any regression when implemented on its own in the docsite:

https://github.com/AlaskaAirlines/auro-select/assets/124668226/bbb238c9-6090-4d60-b069-cee2efb3ebd6

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Review by blackfalcon — APPROVED** [review]
Changes appear to be addressing the issue and do not have adverse side-effects on UIs not contained within a dialog element.

**Review by jason-capsule42 — CHANGES_REQUESTED** [review]
@fajar-apri-alaska 

I'm struggling to validate that this fix is actually correct. 

I am unable to setup a working example that is broken without the style changes and works correctly with them.

The change should include some sort of example that demonstrates this now works. If you add an example to the docpage then we should be able to run this locally and simply comment out the style changes and see it broken.

**Comment by fajar-apri-alaska** [comment]
> @fajar-apri-alaska
> 
> I'm struggling to validate that this fix is actually correct.
> 
> I am unable to setup a working example that is broken without the style changes and works correctly with them.
> 
> The change should include some sort of example that demonstrates this now works. If you add an example to the docpage then we should be able to run this locally and simply comment out the style changes and see it broken.

@jason-capsule42, Is it really needed it put example in the docsite?

To be honest, I was also struggling to replicate the issue in the docsite,
before below PR comes from the reporter itself to help reproduce it:
https://github.com/Alaska-ECommerce/LoungeMembership-Web/pull/386

**Pull request merged**
